# Alias definitions.
alias clc='tput reset'
alias cp='cp -i'
alias du='du -h --max-depth=1'
alias g++11='g++ -std=c++11 -o main'
alias ipythonspark='ipython=1 IPYTHON_OPTS=--\"pylab\" /opt/spark/spark-1.6.0/bin/pyspark'
alias l='ls -CF'
alias l='ls -CF'
alias la='ls -A'
alias la='ls -A'
alias le='less -SN'
alias les='less -S'
alias ll='ls -alF'
alias ll='ls -alF'
alias lll='ll -h'
alias mv='mv -i'
alias notebook='cd ~/Desktop/notebook/'
alias notecpp='cd ~/Desktop/notebook/cpp/;vi cpp.tex'
alias notelatex='cd ~/Desktop/notebook/latex/;vi latex.tex'
alias notelinux='cd ~/Desktop/notebook/linux/;vi linux.tex'
alias notepython='cd ~/Desktop/notebook/python/;vi python.tex'
alias notevi='cd ~/Desktop/notebook/vim/;vi vim.tex'
alias py='python '
alias renetwork='sudo service network-manager restart'
alias rm='rm -i'
alias sbwt='cd ~/Program/cpp/sbwt/sbwa/'
alias sbwtIndex='cd ~/Program/cpp/sbwt/sbwa-buildIndex/'
alias srcbash='source ~/.bashrc'
alias vb='vi ~/.bashrc'
alias vibash='vi ~/.bashrc'
alias vs='source ~/.bashrc'
alias wl='wc -l'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"' # Add an "alert" alias for long running commands.  Use like so: #   sleep 10; alert
